
package Presentacion.Liquidaciones;

import Dominio.Retencion;
import Logica.LogCodigo;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class InternalModRetencion extends javax.swing.JInternalFrame {
    private Retencion retencion;
    private static InternalModRetencion instancia=null;
    private InternalRetencionesFijas inte;
    private LogCodigo log;
    public InternalModRetencion(Retencion ret, InternalRetencionesFijas internal,LogCodigo log) {
        initComponents();
        this.retencion=ret;
        this.inte=internal;
        this.log=log;
        this.cargarRetencion();
    }

     public static InternalModRetencion instancia(Retencion ret, InternalRetencionesFijas internal,LogCodigo log) throws ClassNotFoundException, SQLException
    {    
         if (instancia== null)
         {
            instancia = new InternalModRetencion(ret,internal,log);
         }
         return instancia;
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkSueldo = new javax.swing.JCheckBox();
        checkAgui = new javax.swing.JCheckBox();
        radioActiva = new javax.swing.JRadioButton();
        radioInactiva = new javax.swing.JRadioButton();
        radioImporte = new javax.swing.JRadioButton();
        radioPorcentaje = new javax.swing.JRadioButton();
        txtValor = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblFunc = new javax.swing.JLabel();
        btnListar1 = new org.edisoncor.gui.button.ButtonIcon();

        setClosable(true);
        setTitle("Modificar Retención Fija");
        setPreferredSize(new java.awt.Dimension(350, 345));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Funcionario: ");

        checkSueldo.setText("Sueldo");

        checkAgui.setText("Aguinaldo y Vacacional");

        buttonGroup1.add(radioActiva);
        radioActiva.setText("Activa");

        buttonGroup1.add(radioInactiva);
        radioInactiva.setText("Inactiva");

        buttonGroup2.add(radioImporte);
        radioImporte.setText("Importe");
        radioImporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioImporteItemStateChanged(evt);
            }
        });

        buttonGroup2.add(radioPorcentaje);
        radioPorcentaje.setText("Porcentaje");
        radioPorcentaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioPorcentajeItemStateChanged(evt);
            }
        });
        radioPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPorcentajeActionPerformed(evt);
            }
        });

        txtValor.setBackground(new java.awt.Color(102, 153, 255));
        txtValor.setForeground(new java.awt.Color(255, 255, 255));
        txtValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor.setCaretColor(new java.awt.Color(255, 255, 255));
        txtValor.setSelectionColor(new java.awt.Color(102, 102, 102));
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Valor");

        btnListar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new.png"))); // NOI18N
        btnListar1.setText("buttonIcon1");
        btnListar1.setToolTipText("Modificar");
        btnListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioActiva)
                                .addGap(21, 21, 21)
                                .addComponent(radioInactiva))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioImporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioPorcentaje))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkSueldo)
                                .addGap(21, 21, 21)
                                .addComponent(checkAgui))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAgui)
                    .addComponent(checkSueldo))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioActiva)
                    .addComponent(radioInactiva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioImporte)
                    .addComponent(radioPorcentaje))
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPorcentajeActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        int k = (int) evt.getKeyChar();
        String valor = this.txtValor.getText();
        if(!valor.contains(".")){
            if (k >= 97 && k <= 122 || k >= 65 && k <= 90 || k==32||k==45||k==8||k==47||k==42||k==43)  {
                evt.consume();
            }
        }
        else{
            if (k >= 97 && k <= 122 || k >= 65 && k <= 90 || k==46 || k==32||k==45||k==8||k==47||k==42||k==43)  {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtValorKeyTyped

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        instancia=null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void radioImporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioImporteItemStateChanged
        this.txtValor.setText("");
        this.txtValor.requestFocus();
    }//GEN-LAST:event_radioImporteItemStateChanged

    private void radioPorcentajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioPorcentajeItemStateChanged
        this.txtValor.setText("");
        this.txtValor.requestFocus();
    }//GEN-LAST:event_radioPorcentajeItemStateChanged

    private void btnListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar1ActionPerformed
        try {
            Retencion r=new Retencion();
            String valor=this.txtValor.getText();
            r.setCod(retencion.getCod());
            r.setFunc(retencion.getFunc());
            if(this.checkSueldo.isSelected()){
                r.setSueldo(1);
            }
            else{
                r.setSueldo(0);
            }
            if(this.checkAgui.isSelected()){
                r.setOtros(1);
            }
            else{
                r.setOtros(0);
            }
            if(this.radioActiva.isSelected()){
                r.setActiva(1);
            }
            else{
                r.setActiva(0);
            }
            if(this.radioImporte.isSelected()){
                r.setTipo(0);
                r.setPorcentaje(0.0);
                r.setImporte(Double.valueOf(valor));
            }
            else{
                r.setTipo(1);
                Double por=Double.valueOf(valor);
                if(por<1){
                r.setPorcentaje(por);
                }
                else{
                r.setPorcentaje(por/100);    
                }
                r.setImporte(0.0);
            }
            
            if(this.log.actualizaRetencion(r)){
                this.dispose();
                this.inte.setRetMod(r);
                this.inte.getBtnListar().doClick();
                
            }} catch (ClassNotFoundException ex) {
            Logger.getLogger(InternalModRetencion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(InternalModRetencion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIcon btnListar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkAgui;
    private javax.swing.JCheckBox checkSueldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblFunc;
    private javax.swing.JRadioButton radioActiva;
    private javax.swing.JRadioButton radioImporte;
    private javax.swing.JRadioButton radioInactiva;
    private javax.swing.JRadioButton radioPorcentaje;
    private org.edisoncor.gui.textField.TextFieldRound txtValor;
    // End of variables declaration//GEN-END:variables

    private void cargarRetencion() {
        this.lblCod.setText(this.retencion.getCod().toString());
        this.lblFunc.setText(this.retencion.getFunc().getCodFunc()+ " - "+this.retencion.getFunc().getNombre1());
        if(this.retencion.getSueldo()==1){
            this.checkSueldo.setSelected(true);
        }
        if(this.retencion.getOtros()==1){
            this.checkAgui.setSelected(true);
        }
        if(retencion.getActiva()==1){
            this.radioActiva.setSelected(true);
            this.radioInactiva.setSelected(false);
        }
        else{
            this.radioInactiva.setSelected(true);
            this.radioActiva.setSelected(false);
        }
        if(retencion.getTipo()==1){
            this.radioPorcentaje.setSelected(true);
            this.txtValor.setText(retencion.getPorcentaje().toString());
        }
        else{
            this.radioImporte.setSelected(true);
            this.txtValor.setText(retencion.getImporte().toString());
        }
    }
}
