
package Presentacion.Marcas;

import Dominio.Marca;
import Logica.LogTripaliare;
import Presentacion.Licencias.InternalMovLicencia;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;


public class InternalSupervisar extends javax.swing.JInternalFrame {
    private static InternalSupervisar instancia=null;
    public Marca marca;
    public String nombre;
    public Date date;
    private InternalMarcas internal;
    private LogTripaliare log;
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public InternalSupervisar(LogTripaliare lo,InternalMarcas inter) throws ClassNotFoundException, SQLException {
        initComponents();
        this.btnInvisible.setVisible(false);
        this.txtCodFunc.setEnabled(false);
        this.date=new Date();
        this.log=lo;
        this.internal=inter;
    }

    public JButton getBtnInvisible() {
        return btnInvisible;
    }

    public void setBtnInvisible(JButton btnInvisible) {
        this.btnInvisible = btnInvisible;
    }
    
    
    public static InternalSupervisar instancia(LogTripaliare lo,InternalMarcas inter) throws ClassNotFoundException, SQLException
   {    
         if (instancia== null)
         {
            instancia = new InternalSupervisar(lo,inter);
         }
         return instancia;
      
   }

    public Marca getMarca() {
        return marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCodFunc = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFechaActualiz = new com.toedter.calendar.JDateChooser();
        txtHora = new org.edisoncor.gui.textField.TextFieldRound();
        lblNombres = new javax.swing.JLabel();
        btnAceptar = new org.edisoncor.gui.button.ButtonIcon();
        btnInvisible = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDiferencia = new org.edisoncor.gui.textField.TextFieldRound();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel2.setText("Cod.Funcionario");

        txtCodFunc.setBackground(new java.awt.Color(102, 153, 255));
        txtCodFunc.setForeground(new java.awt.Color(255, 255, 255));
        txtCodFunc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCodFunc.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel3.setText("Tipo");

        jLabel6.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel6.setText("Hora Marca");

        txtFecha.setDateFormatString("dd/MM/yyyy");
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel7.setText("Fecha Marca");

        jLabel8.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel8.setText("Fecha de Actualización");

        txtFechaActualiz.setDateFormatString("dd/MM/yyyy");

        txtHora.setBackground(new java.awt.Color(102, 153, 255));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setCaretColor(new java.awt.Color(255, 255, 255));
        txtHora.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraKeyTyped(evt);
            }
        });

        lblNombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ok.png"))); // NOI18N
        btnAceptar.setText("buttonIcon1");
        btnAceptar.setToolTipText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnInvisible.setText("jButton1");
        btnInvisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvisibleActionPerformed(evt);
            }
        });

        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RELOJ", "FERIADO", "RELOJ SUP", "FALTA", "INTERIOR", "VACIA", "LICENCIA" }));

        jLabel9.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel9.setText("Diferencia");

        txtDiferencia.setBackground(new java.awt.Color(102, 153, 255));
        txtDiferencia.setForeground(new java.awt.Color(255, 255, 255));
        txtDiferencia.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDiferencia.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtDiferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiferenciaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel4.setText("Observación:");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInvisible)
                        .addGap(261, 261, 261)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(64, 64, 64)
                                    .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(183, 183, 183)
                                    .addComponent(txtFechaActualiz, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboTipo, 0, 190, Short.MAX_VALUE)
                                        .addComponent(txtDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaActualiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInvisible)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInvisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvisibleActionPerformed
       if(this.marca!=null){
           this.lblNombres.setText(this.nombre);
           this.txtCodFunc.setText(marca.getFunCod().toString());
           this.txtFecha.setDate(this.marca.getFechaUso());
           this.txtHora.setText(this.marca.getHoraUso());
           this.txtFechaActualiz.setDate(this.marca.getFecha());
           this.txtDiferencia.setText(this.marca.getIncongruencia().toString());
           this.txtFechaActualiz.setEnabled(false);
          
          
           this.txtArea.setText(this.marca.getObservacion()); 
           
           switch(marca.getTipo()){
               case "RELOJ":
               this.comboTipo.setSelectedIndex(0);
               break;
               case "FERIADO":
               this.comboTipo.setSelectedIndex(1);
               break;
               case "RELOJ SUP":
               this.comboTipo.setSelectedIndex(2);
               break;
               case "FALTA":
               this.comboTipo.setSelectedIndex(3);
               break;
               case "INTERIOR":
               this.comboTipo.setSelectedIndex(4);
               break;
               case "VACIA":
               this.comboTipo.setSelectedIndex(5);
               break;  
               case "LICENCIA":
               this.comboTipo.setSelectedIndex(6);
               break;
               }
       }
    }//GEN-LAST:event_btnInvisibleActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
      Marca m=new Marca();
        m.setFecha(date); 
        m.setFechaUso(this.txtFecha.getDate());
        m.setHoraUso(this.txtHora.getText());
        m.setId(this.marca.getId());
        m.setFunCod(marca.getFunCod());
        m.setTipo(this.comboTipo.getSelectedItem().toString());
        m.setIncongruencia(Integer.valueOf(this.txtDiferencia.getText()));
        m.setObservacion(this.txtArea.getText());
        
        Date marc=marca.getFechaUso();
        Date marc1=m.getFechaUso();
        String hor=marca.getHoraUso();
        String hor1=m.getHoraUso();
        String tipo=marca.getTipo();
        String tipo1=m.getTipo();
        Integer m1=marca.getIncongruencia();
        Integer m2=m.getIncongruencia();
        String obs=marca.getObservacion();
        
        if(!this.convertirFecha(marc).equals(this.convertirFecha(marc1))|| !hor.equals(hor1)|| !tipo.equals(tipo1)|| !m2.equals(m1) || !obs.equals(m.getObservacion())){
            if(this.validarHora(m.getHoraUso())){
                m.setSupervisado(1);
                m.setMarcaFecha(this.fijaHora(m.getFechaUso(), m.getHoraUso()));
                try {
                    if(this.log.actualizaMarca(m,marca)==1){
                        this.lblMensaje.setText("Actualización exitosa");
                        this.internal.getBtnListar().doClick();
                        this.marca=m;
                        this.txtHora.requestFocus();
                    }
                    else{
                        this.lblMensaje.setText("No se ha podido actualizar la marca");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(InternalSupervisar.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(InternalSupervisar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
            this.lblMensaje.setText("Verifique que el formato de la hora sea 00:00:00");
        }
            
            
            
        }
        else{
            this.lblMensaje.setText("No hay nada para modificar");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        instancia=null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void txtDiferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiferenciaKeyTyped
        char c=evt.getKeyChar();
        if(evt.getKeyChar()==27){
            this.dispose();
        }
        if(!Character.isDigit(c)){
           evt.consume();
       }
     
    }//GEN-LAST:event_txtDiferenciaKeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        if(evt.getKeyChar()==27){
            this.dispose();
        }
    }//GEN-LAST:event_txtFechaKeyTyped

    private void txtHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyTyped
       if(evt.getKeyChar()==27){
            this.dispose();
        }
    }//GEN-LAST:event_txtHoraKeyTyped

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
           if(evt.getKeyChar()==27){
            this.dispose();
        }
    }//GEN-LAST:event_txtFechaKeyPressed

    private void txtAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyTyped
        String texto = this.txtArea.getText();
        if(texto.length()>0){
            if(texto.length()%25==0){
                this.txtArea.setText(texto+"\n");
            }
        }
        if(texto.length()>=299){
            evt.consume();
        }
    }//GEN-LAST:event_txtAreaKeyTyped

    private Timestamp fijaHora(Date date, String hora){
    Calendar c=Calendar.getInstance();
    c.setTimeInMillis(date.getTime());
    c.set(Calendar.HOUR_OF_DAY, Integer.valueOf(this.armaHora(hora,0,1)));
    c.set(Calendar.MINUTE, Integer.valueOf(this.armaHora(hora,3,4)));
    c.set(Calendar.SECOND, Integer.valueOf(this.armaHora(hora,6,7)));
    c.set(Calendar.MILLISECOND, 0);
    Timestamp ts = new java.sql.Timestamp(date.getTime());
    ts.setTime(c.getTimeInMillis());
    return ts;
    }
        
    private String armaHora(String hora, Integer pos1,Integer pos2){
        String retorno=String.valueOf(hora.charAt(pos1));
        retorno+=String.valueOf(hora.charAt(pos2));
        return retorno;
    }
    
     private String convertirFecha(Date fecha){
   String str=null;
        if(fecha!=null){
         SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy"); 
         str= sdf.format(fecha);
        }
    
    return str;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIcon btnAceptar;
    private javax.swing.JButton btnInvisible;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextArea txtArea;
    private org.edisoncor.gui.textField.TextFieldRound txtCodFunc;
    private org.edisoncor.gui.textField.TextFieldRound txtDiferencia;
    private com.toedter.calendar.JDateChooser txtFecha;
    private com.toedter.calendar.JDateChooser txtFechaActualiz;
    private org.edisoncor.gui.textField.TextFieldRound txtHora;
    // End of variables declaration//GEN-END:variables

     private Boolean validarHora(String str){
    Boolean valida=false;
    Integer largo=str.length();
   
    if(largo==8){
       Character c1=str.charAt(5);
       Character c=str.charAt(2);
        if(c.equals(':')&& c1.equals(':')){
            if(Character.isDigit(str.charAt(0))&& Character.isDigit(str.charAt(1))&& Character.isDigit(str.charAt(3))&&Character.isDigit(str.charAt(4)) && Character.isDigit(str.charAt(6))&&Character.isDigit(str.charAt(7))){
            valida=true;
        }
        }
    }  
    return valida;
    }
}
